language: cpp
compiler: clang
before_install:
  - ./travis-ci/travis_install_packages.sh
  - ./travis-ci/travis_build_ninja.sh
  - ./travis-ci/travis_build_libcxx.sh
  - ./travis-ci/travis_build_boost.sh
script: CC=/usr/bin/clang-3.4 CXX=/usr/bin/clang++-3.4 cmake -G "Ninja" -DBUILD_TESTING=YES . && ninja && ctest
notifications:
  email: false
