language: cpp
compiler: clang
cache: apt
before_install:
  - ./travis-ci/travis_install_packages.sh
  - ./travis-ci/travis_build_ninja.sh
  - ./travis-ci/travis_build_libcxx.sh
  - ./travis-ci/travis_build_boost.sh
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -G "Ninja" -DTRAVIS_CI=YES -DCMAKE_BUILD_TYPE=Debug -DTEST_COVERAGE=YES -DBUILD_TESTING=YES . && ninja && ASAN_OPTIONS=alloc_dealloc_mismatch=0 ctest -V
after_success:
  - coveralls --build-root `pwd` --exclude-pattern "^/usr/" --verbose
notifications:
  email: false
